<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>SoftDevs — About Us</title>
  <link rel="stylesheet" href="styles.css" />


</head>

<body>

    <header>
<a href="index.php">
        <span class="logo" aria-hidden="true">
          <img src="logo.png" alt="SoftDevs logo" />
        </span>

        <span id="companyname">SoftDevs</span>

      </a>
      <h1>Your Future Starts Here!</h1>
<br><br>